theme: jekyll-theme-minimal
title: "The Art of Go"
description: "Ancient strategy meets modern wisdom"
baseurl: ""
url: "https://[your-username].github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude files
exclude:
  - README.md